#!/bin/ksh
#set -x
#sn0=$(netstat -in |grep sn0 |grep -v link |awk '{print $4}')
echo "Lets flood ping the ml0 interface  from $(hostname -s) ml0 "
for i in `cat /usrtools/fedtools/up.intml0` 
do
out=`ping -f -c 1000 -s 8000 $i | grep "% packet" | grep -v " 0%"`
echo "pinging interface ip address $i"
#out=`ping -c 1 $i | grep "% packet" | grep -v " 0%"`
if [ "$out" != "" ]
then
    echo "Flood ping to $i - $out"
fi
done
echo

#---------------------------------------------------------------------------------------

