#!/bin/ksh
#set -x
echo "Lets single ping to ml0 interfaces from $(hostname -s) ml0 "
for i in `cat /usrtools/fedtools/up.intml0` 
do
out=`ping -c 1 -s 3000 $i | grep "% packet" | grep -v " 0%"`
echo "pinging interface ip address $i"
#out=`ping -c 1 $i | grep "% packet" | grep -v " 0%"`
if [ "$out" != "" ]
then
    echo "Flood ping to $i - $out"
fi
done
echo

#---------------------------------------------------------------------------------------

