#!/bin/ksh

# Check number of paramters
if( test $# -lt 2 )
        then
                echo "Usage: $0 offset value"
                echo "       Offset must be in hex! (with leading 0x)"
                echo "       Value must be in hex! (with leading 0x)"
                exit
fi

offset=$1
value=$2

off_is_hex=`echo $offset | cut -c1,2 `
val_is_hex=`echo $value | cut -c1,2 `

if [[ $off_is_hex != "0x" || $val_is_hex != "0x" ]]
then 
        echo "Offset must be in hex! (with leading 0x)!"
	echo "Value must be in hex! (with leading 0x)!"
        exit
fi

for xxx in 0 1 2 3 4 5 6 7
do
	avail=`lsdev -C | grep sni$xxx | awk '{print $2}'`
	if [[ $avail = "Available" ]]
	then
		/usrtools/fedtools/fedwrite -l sni${xxx} -o ${offset} -v ${value} -d 1
	fi
done
